// Wispucci — единое приложение. Флоу: уровень→предмет→профиль→тема→урок/тизер→диагностика.
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const SK='wispucci.state';
function sdef(){return{level:null,profile:null,signedUp:false,mastery:{},done:[],correct:0,total:0};}
function sload(){try{return JSON.parse(localStorage.getItem(SK))||sdef();}catch(_){return sdef();}}
function ssave(){localStorage.setItem(SK,JSON.stringify(S));}
let S=sload();
let selLevel=null,selSubject=null,selTopic=null,steps=[],stepIdx=0;
const hasAPI=typeof window.API!=='undefined';
const loggedIn=()=>hasAPI&&typeof Auth!=='undefined'&&Auth.isLoggedIn;

// ---- часы ----
function clock(){const n=new Date();const c=$('#clock');if(c)c.textContent=String(n.getHours()).padStart(2,'0')+':'+String(n.getMinutes()).padStart(2,'0');}
clock();setInterval(clock,30000);

// ---- фон ----
(function(){const c=$('#bg');if(!c)return;const x=c.getContext('2d'),dpr=Math.min(devicePixelRatio,2);let W,H,ps=[];function rs(){W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;c.style.width=W+'px';c.style.height=H+'px';x.setTransform(dpr,0,0,dpr,0,0);}rs();addEventListener('resize',rs);const N=Math.round(22*(innerWidth/1400));for(let i=0;i<N;i++)ps.push(mk(true));function mk(init){return{x:Math.random()*innerWidth,y:init?Math.random()*innerHeight:innerHeight+40,r:.4+Math.random()*1,vy:-(.05+Math.random()*.18),vx:(Math.random()-.5)*.07,a:.1+Math.random()*.35,f:Math.random()*6.28};}function draw(){x.clearRect(0,0,W,H);x.globalCompositeOperation='lighter';for(let i=0;i<ps.length;i++){const p=ps[i];p.x+=p.vx;p.y+=p.vy;p.f+=.03;const a=(Math.sin(p.f)*.2+.7)*p.a*.4;x.fillStyle=`rgba(239,221,141,${a})`;x.beginPath();x.arc(p.x,p.y,p.r,0,6.28);x.fill();if(p.y<-10)ps[i]=mk(false);}x.globalCompositeOperation='source-over';requestAnimationFrame(draw);}draw();})();

// ---- орб (всегда в углу, НЕ перекрывает контент) ----
const orb=$('#orb');
function orbState(s){if(!orb)return;['happy','thinking','speaking','confused','celebrating'].forEach(k=>orb.classList.toggle('is-'+k,k===s));}
let speechT;
function orbSpeak(text){const sp=$('#orbSpeech');if(!sp)return;sp.textContent=text;sp.classList.add('show');orbState('speaking');clearTimeout(speechT);speechT=setTimeout(()=>{sp.classList.remove('show');orbState('happy');},4600);}
(function blink(){setTimeout(()=>{const e=orb&&orb.querySelector('.face-eyes');if(e){e.style.transform='scaleY(.05)';setTimeout(()=>{e.style.transform='';},110);}blink();},2600+Math.random()*3400);})();

// ---- навигация ----
function go(screen){$$('.screen').forEach(s=>s.classList.toggle('is-active',s.dataset.screen===screen));window.scrollTo({top:0,behavior:'smooth'});}
$$('[data-back]').forEach(b=>b.addEventListener('click',()=>{const to=b.getAttribute('data-back');go(to);if(to==='levels')renderLevels();if(to==='subjects')renderSubjects();if(to==='topics')renderTopics();}));

// ---- 1: уровни ----
function renderLevels(){const el=$('#levelGrid');el.innerHTML=LEVELS.map(l=>`<button class="level-card" data-level="${l.id}"><span class="level-short">${l.short}</span><span class="level-name">${l.name}</span><span class="level-blurb">${l.blurb}</span><span class="level-go">Alege →</span></button>`).join('');$$('.level-card').forEach(c=>c.addEventListener('click',()=>{selLevel=LEVELS.find(l=>l.id===c.dataset.level);S.level=selLevel.id;ssave();renderSubjects();go('subjects');}));}

// ---- 2: предметы ----
function renderSubjects(){if(!selLevel)selLevel=LEVELS.find(l=>l.id===S.level)||LEVELS[0];$('#subjectsTitle').textContent=selLevel.name;$('#subjectGrid').innerHTML=selLevel.subjects.map(s=>`<button class="subj-card" data-sub="${s.id}"><span class="subj-sym">${s.symbol}</span><span class="subj-name">${s.name}</span><span class="subj-tags">${s.profiles?'<span class="subj-tag">real / umanist</span>':''}${s.atlas?'<span class="subj-tag">atlas permis</span>':''}</span></button>`).join('');$$('.subj-card').forEach(c=>c.addEventListener('click',()=>chooseSubject(c.dataset.sub)));}
function chooseSubject(id){selSubject=selLevel.subjects.find(s=>s.id===id);if(selSubject.profiles&&!S.profile){renderProfile();go('profile');return;}renderTopics();go('topics');}

// ---- 2.5: профиль ----
function renderProfile(){$('#profileStage').innerHTML=`<div class="prof-wrap"><h2>Ce profil ai?</h2><p>Contează: la real și umanist se dau examene diferite.</p><div class="prof-opts"><button class="prof-opt" data-prof="real"><b>Real</b><span>Matematică, științe exacte</span></button><button class="prof-opt" data-prof="uman"><b>Umanist</b><span>Litere, științe umane</span></button></div></div>`;$$('.prof-opt').forEach(b=>b.addEventListener('click',()=>{S.profile=b.dataset.prof;ssave();renderTopics();go('topics');}));}

// ---- 3: темы ----
function visibleTopics(){let t=selSubject.topics;if(selSubject.profiles&&S.profile)t=t.filter(x=>!x.profile||x.profile==='both'||x.profile===S.profile);return t;}
function renderTopics(){$('#topicsTitle').textContent=selSubject.name;$('#topicsSub').textContent=(S.profile&&selSubject.profiles?'Profil: '+S.profile:'')+(selSubject.atlas?' · atlas permis':'');$('#topicList').innerHTML=visibleTopics().map(t=>{const m=S.mastery[t.id];const badge=(loggedIn()&&m!=null)?`<span class="topic-mastery">${Math.round(m*100)}%</span>`:'';const dn=S.done.includes(t.id)?'<span class="topic-done">✓</span>':'';return `<button class="topic-row" data-topic="${t.id}"><span class="topic-title">${t.title}</span>${dn}${badge}<span class="topic-go">→</span></button>`;}).join('');$$('.topic-row').forEach(r=>r.addEventListener('click',()=>chooseTopic(r.dataset.topic)));}
function chooseTopic(id){selTopic=visibleTopics().find(t=>t.id===id);startLearning();}

// ---- обучение ----
function startLearning(){const lesson=STEP_LESSONS[selTopic.id];if(selLevel.id==='gimnaziu'&&lesson){steps=[...lesson];stepIdx=0;runSteps();return;}if(!loggedIn()){renderTeaser();go('teaser');return;}renderBackendLesson();}

// ---- движок пошагового урока ----
function runSteps(){$('#lessonTitle').textContent=selTopic.title;$('#stepDots').innerHTML=steps.map(()=>`<span class="step-dot"></span>`).join('');go('lesson');renderStep();}
function renderStep(){const st=steps[stepIdx];let h='';const kick=st.kicker||(st.type==='pretest'?'Ghici întâi':st.type==='elaborate'?'De ce?':'');if(kick)h+=`<span class="step-kicker">${kick}</span>`;h+=`<h3 class="step-title">${st.title||''}</h3>`;if(st.type==='quiz'||st.type==='pretest'){h+=`<p class="step-q">${st.q}</p><div class="step-opts">${st.opts.map((o,i)=>`<button class="step-opt" data-i="${i}">${o}</button>`).join('')}</div><div class="step-fb"></div>`;}else if(st.type==='completion'){h+=`<p class="step-body">${st.body.replace(/__/g,()=>`<input class="fill" size="4">`)}</p><button id="fillCheck" class="btn-ghost">Verifică</button><div class="step-fb"></div>`;}else if(st.type==='elaborate'){h+=`<p class="step-q">${st.q}</p><button id="elabReveal" class="btn-ghost">Arată răspunsul</button><div class="step-fb"></div>`;}else{h+=`<div class="step-body">${st.body}</div>`;}$('#lessonStage').innerHTML=`<div class="step-card">${h}</div>`;$$('#stepDots .step-dot').forEach((d,i)=>d.className='step-dot'+(i<stepIdx?' done':i===stepIdx?' current':''));const nb=$('#stepNext');const needs=(st.type==='quiz'||st.type==='pretest'||st.type==='completion'||st.type==='elaborate');nb.style.opacity=needs?'.4':'1';nb.style.pointerEvents=needs?'none':'all';nb.textContent=stepIdx>=steps.length-1?'Termină tema ✓':'Continuă →';$('#lessonHint').textContent=st.type==='pretest'?'Ghicește, chiar dacă nu ești sigur':st.type==='completion'?'Completează spațiile':st.type==='elaborate'?'Gândește, apoi verifică':st.type==='quiz'?'Alege un răspuns':'Citește, apoi continuă';if(st.type==='quiz'||st.type==='pretest'){orbState('thinking');$$('.step-opt').forEach(b=>b.addEventListener('click',()=>answer(b,st)));if(st.speak)setTimeout(()=>orbSpeak(st.speak),500);else if(st.type==='pretest')setTimeout(()=>orbSpeak('N-ai de unde să știi încă. Ghicește oricum.'),500);}else if(st.type==='completion'){orbState('thinking');$('#fillCheck').addEventListener('click',()=>checkFill(st));if(st.speak)setTimeout(()=>orbSpeak(st.speak),500);}else if(st.type==='elaborate'){orbState('thinking');$('#elabReveal').addEventListener('click',()=>{const fb=$('.step-fb');fb.classList.add('show');fb.textContent=st.reveal;$('#elabReveal').style.display='none';unlockNext();orbState('happy');});if(st.speak)setTimeout(()=>orbSpeak(st.speak),500);}else{orbState('happy');if(st.speak)setTimeout(()=>orbSpeak(st.speak),500);}}
function unlockNext(){const nb=$('#stepNext');nb.style.opacity='1';nb.style.pointerEvents='all';}
function answer(btn,st){const i=+btn.dataset.i,ok=i===st.correct,fb=$('.step-fb');$$('.step-opt').forEach((o,idx)=>{o.disabled=true;if(idx===st.correct)o.classList.add('correct');});if(!ok)btn.classList.add('wrong');fb.classList.add('show');if(st.type==='pretest'){fb.className='step-fb show '+(ok?'ok':'');fb.textContent=st.exp;orbState(ok?'celebrating':'happy');setTimeout(()=>orbSpeak(ok?'Ai nimerit din instinct. Hai să vezi de ce.':'Perfect că ai încercat. Acum creierul caută răspunsul.'),300);}else{if(ok){fb.className='step-fb show ok';fb.textContent='Corect. '+st.exp;S.correct++;orbState('celebrating');setTimeout(()=>orbSpeak('Frumos. Ai prins ideea.'),300);}else{fb.className='step-fb show no';fb.textContent=st.exp;orbState('confused');setTimeout(()=>orbSpeak('Nu-i nimic. Reține explicația, revenim la asta.'),300);}S.total++;ssave();}unlockNext();$('#lessonHint').textContent='';}
function checkFill(st){const ins=$$('.fill'),fb=$('.step-fb');let ok=true;ins.forEach((inp,i)=>{if(inp.value.trim()===(st.blanks[i]||'')){inp.classList.add('ok');}else{inp.classList.add('no');ok=false;}});fb.classList.add('show');if(ok){fb.className='step-fb show ok';fb.textContent='Exact. Ai completat corect.';S.correct++;S.total++;ssave();orbState('celebrating');unlockNext();setTimeout(()=>orbSpeak('Vezi? Cu puțin ajutor ai reușit singur.'),300);}else{fb.className='step-fb show no';fb.textContent=st.hint||'Aproape. Mai încearcă.';orbState('confused');setTimeout(()=>orbSpeak(st.hint||'Aproape. Uită-te din nou.'),300);}}
$('#stepNext').addEventListener('click',()=>{if(stepIdx>=steps.length-1){finishTopic();return;}const card=$('.step-card');if(card)card.classList.add('leaving');stepIdx++;setTimeout(renderStep,220);});
function finishTopic(){if(!S.done.includes(selTopic.id))S.done.push(selTopic.id);ssave();orbState('celebrating');orbSpeak('Temă terminată. Ești tot mai aproape de examen.');if(!S.signedUp&&!loggedIn()){setTimeout(openSignup,900);return;}setTimeout(()=>{renderTopics();go('topics');},1200);}

// ---- тизер гостя ----
function renderTeaser(){$('#teaserStage').innerHTML=`<div class="teaser"><span class="teaser-kicker">${selSubject.name}${S.profile&&selSubject.profiles?' · '+S.profile:''}</span><h2>${selTopic.title}</h2><p class="teaser-body">Aici începe de la bază: înțelegi conceptul, ghicești, apoi Wispucci îți arată de ce. După ce te înscrii, îți măsoară nivelul printr-un test scurt și îți construiește un plan doar pentru tine.</p><div class="teaser-lock">🔒 Lecția completă și planul personalizat se deblochează după înscriere (gratis).</div><button id="teaserSignup" class="btn-primary">Deblochează și află-ți nivelul</button></div>`;$('#teaserSignup').addEventListener('click',()=>{pendingAfterSignup=afterSignup;openSignup();});setTimeout(()=>orbSpeak('Aici te prind. Vrei planul tău? Înscrie-te, durează 10 secunde.'),600);}

// ---- диагностика (после регистрации) ----
async function afterSignup(){S.signedUp=true;ssave();await runDiagnostic();}
async function runDiagnostic(){go('diag');$('#diagStage').innerHTML=`<div class="diag-intro"><h2>Hai să văd unde ești</h2><p>Câteva întrebări scurte la ${selSubject.name}. Nu-i test cu notă, doar ca să-ți construiesc planul. Dacă nu știi, spune.</p><button id="diagStart" class="btn-primary">Încep</button></div>`;$('#diagStart').addEventListener('click',diagItems);orbState('happy');setTimeout(()=>orbSpeak('Fără stres. Cinstit îți dă planul cel mai bun.'),500);}
async function diagItems(){let items=null;if(loggedIn()&&API.diagnosticStart){try{const r=await API.diagnosticStart(selSubject.id,S.profile);items=r&&r.items;}catch(_){}}if(!items)items=visibleTopics().slice(0,6).map(t=>({skill_id:t.id,title:t.title}));let i=0;const answers=[],stage=$('#diagStage');function show(){if(i>=items.length){finishDiag(answers);return;}const it=items[i];stage.innerHTML=`<div class="diag-item"><span class="diag-count">${i+1} / ${items.length}</span><h3>${it.title}</h3><p class="diag-q">Cât de sigur te simți la tema asta?</p><div class="diag-scale"><button data-v="0">Habar n-am</button><button data-v="0.4">Am auzit</button><button data-v="0.7">Cam știu</button><button data-v="0.95">O stăpânesc</button></div></div>`;$$('.diag-scale button').forEach(b=>b.addEventListener('click',()=>{answers.push({skill_id:it.skill_id,confidence:+b.dataset.v});i++;show();}));}show();}
async function finishDiag(answers){answers.forEach(a=>S.mastery[a.skill_id]=a.confidence);ssave();if(loggedIn()&&API.diagnosticSubmit){try{await API.diagnosticSubmit(selSubject.id,S.profile,answers);}catch(_){}}const weak=[...answers].sort((a,b)=>a.confidence-b.confidence).slice(0,3);$('#diagStage').innerHTML=`<div class="diag-done"><h2>Gata. Am planul tău.</h2><p>Începem cu ce te clatină cel mai tare, apoi urcăm treptat.</p><ol class="diag-plan">${weak.map(w=>{const t=visibleTopics().find(x=>x.id===w.skill_id);return `<li>${t?t.title:w.skill_id}</li>`;}).join('')}</ol><button id="diagGo" class="btn-primary">Începe primul subiect</button></div>`;$('#diagGo').addEventListener('click',()=>{const first=weak[0];selTopic=visibleTopics().find(x=>x.id===first.skill_id)||selTopic;const lesson=STEP_LESSONS[selTopic.id];if(lesson){steps=[...lesson];stepIdx=0;runSteps();}else renderBackendLesson();});orbState('celebrating');setTimeout(()=>orbSpeak('Am harta ta. Începem cu punctul slab, acolo crești cel mai repede.'),400);}

// ---- урок с backend ----
async function renderBackendLesson(){go('lesson');$('#lessonTitle').textContent=selTopic.title;$('#stepDots').innerHTML='';$('#lessonHint').textContent='';$('#stepNext').style.display='none';$('#lessonStage').innerHTML=`<div class="bl-load">Pregătesc lecția pentru <b>${selTopic.title}</b>...</div>`;const level=(S.mastery[selTopic.id]!=null)?S.mastery[selTopic.id]:0.3;let lesson=null;if(loggedIn()&&API.generateLesson){try{lesson=await API.generateLesson(selSubject.id,selTopic.title,level);}catch(_){}}if(lesson&&lesson.sections){$('#lessonStage').innerHTML=`<div class="bl"><span class="step-kicker">${selSubject.name}${S.profile?' · '+S.profile:''}</span>${lesson.sections.map(s=>`<div class="bl-sec"><h3>${s.title||''}</h3><div>${s.body||''}</div></div>`).join('')}</div>`;}else{$('#lessonStage').innerHTML=`<div class="bl"><span class="step-kicker">${selSubject.name}${S.profile?' · '+S.profile:''}</span><p class="bl-fallback">Lecția interactivă pentru această temă se generează pe server (pornește backend-ul). Conținutul e deja în baza de cunoștințe, verificat pe baremele ANCE.</p></div>`;}$('#stepNext').style.display='';$('#stepNext').textContent='← Altă temă';$('#stepNext').style.opacity='1';$('#stepNext').style.pointerEvents='all';$('#stepNext').onclick=()=>{renderTopics();go('topics');$('#stepNext').onclick=null;};}

// ---- регистрация ----
let authMode='signup',pendingAfterSignup=null;
function openSignup(){const m=$('#signupModal');m.classList.add('show');$('#suErr').textContent='';$('#suName').style.display=authMode==='login'?'none':'';$('#signupConfirm').textContent=authMode==='login'?'Intră':'Salvează contul';$('#signupToggle').textContent=authMode==='login'?'Nu ai cont? Înscrie-te':'Am deja cont? Intră';}
function closeSignup(){$('#signupModal').classList.remove('show');}
$('#loginTop').addEventListener('click',()=>{authMode='login';openSignup();});
$('#signupToggle').addEventListener('click',()=>{authMode=authMode==='login'?'signup':'login';openSignup();});
$('#signupSkip').addEventListener('click',()=>{closeSignup();if(pendingAfterSignup){const f=pendingAfterSignup;pendingAfterSignup=null;/* гость пропустил: остаётся на темах */go('topics');renderTopics();}});
$('#signupConfirm').addEventListener('click',async()=>{const err=$('#suErr');err.textContent='';const email=$('#suEmail').value.trim(),pass=$('#suPass').value,name=$('#suName').value.trim()||'Elev';if(hasAPI&&API.online&&API.online()){try{let res;if(authMode==='login')res=await API.login(email,pass);else res=await API.signup(email,name,pass);Auth.token=res.access_token;Auth.name=res.display_name;S.signedUp=true;ssave();closeSignup();$('#loginTop').textContent=Auth.name||'Contul meu';const f=pendingAfterSignup||afterSignup;pendingAfterSignup=null;setTimeout(f,400);}catch(e){err.textContent=e.message||'Ceva n-a mers.';}}else{if(!email||!pass){err.textContent='Completează email și parolă.';return;}try{localStorage.setItem('wispucci.token','demo');}catch(_){}S.signedUp=true;ssave();closeSignup();const f=pendingAfterSignup||afterSignup;pendingAfterSignup=null;setTimeout(f,400);}});

// ---- INIT ----
renderLevels();go('levels');orbState('happy');
if(hasAPI&&API.health){API.health().then(on=>{if(on&&typeof Auth!=='undefined'&&Auth.name)$('#loginTop').textContent=Auth.name;});}
